[phases.setup]
packages = [
  "python3",
  "make",
  "gcc",
  "g++"
]

[phases.build]
cmds = [
  "ln -sf $(which python3) /usr/bin/python || true",
  "npm install"
]

[phases.start]
cmd = "npm start"
