[phases.setup]
packages = [
  "python3",
  "make",
  "gcc",
  "g++",
  "pkg-config",
  "libc-dev",
  "linux-headers"
]

[phases.build]
cmds = [
  "ln -sf $(which python3) /usr/bin/python || true",
  "yarn install"  # ← No --frozen-lockfile, allows yarn.lock to update
]

[phases.start]
cmd = "yarn start"
