[phases.setup]
packages = [
  "python3",
  "make",
  "gcc",
  "g++",
  "pkg-config",
  "libc-dev",
  "linux-headers",
  "curl",
  "yarn"
]

[phases.build]
cmds = [
  "ln -sf $(which python3) /usr/bin/python || true",
  "yarn install"
]

[phases.start]
cmd = "yarn start"
