[phases.setup]
packages = [
  "python3",
  "python3-dev",
  "make",
  "gcc",
  "g++",
  "pkg-config",
  "libc-dev",
  "linux-headers",
  "node-gyp",
  "curl"
]

[phases.build]
cmds = [
  "ln -sf $(which python3) /usr/bin/python || true",
  "npm config set python /usr/bin/python",
  "npm install --unsafe-perm --legacy-peer-deps"
]

[phases.start]
cmd = "npm start"
