[phases.setup]
packages = [
  "python3",
  "make",
  "gcc",
  "g++",
  "pkg-config",
  "libc-dev",
  "ffmpeg",
  "linux-headers"
]

[phases.build]
cmds = [
  "ln -sf $(which python3) /usr/bin/python || true",
  "npm install --unsafe-perm"
]

[phases.start]
cmd = "npm start"

[env]
PYTHON = "/usr/bin/python"
